### ISSUE TITLE
Thống nhât kiến trúc project

### ISSUE THREAD

**Issue by hieuhust** [hieuhust/ProjectOne#1]
Theo tôi project mình nên làm theo mô hình MVP. 
Chia thành các các gói chức năng. Mỗi gói chức năng bao gồm các gói nhỏ theo MVP như: view, present, model, dao(tương tác với dữ liệu: từ CSDL or network...).
Ông thấy thế nào?

**Comment by andaupro** [comment]
tôi nghĩ cách chia như vậy hơi bất tiện, nên chia như sau : 

 Dữ liệu (network hoặc cache) ===> Data (gồm các phương thức lấy trực tiếp dữ liệu) ==> Domain (nó gồm các UserCase (interface), đại khái là trung chuyển giữa data và Presenter) ==> Presenter ==> View

==> tóm lại là gom các lớp có cùng chức năng thành 1 khối, vấn đề này có thể đi kĩ vào sprint sau khi demo thành công. (mô hình này tôi thường thấy trên rất nhiều dự án lớn)

**Comment by hieuhust** [comment]
Ý trên của t cũng thế mà. Nhưng ý nói mỗi chức năng gồm 1 gói. 1 gói sẽ bao gồm các gói nhỏ của lớp dữ liệu , data, domain, presenter, view ý.

**Comment by hieuhust** [comment]
Theo dọc
