### ISSUE TITLE
Loading color không đồng nhất giữa các phiên bản android

### ISSUE THREAD

**Issue by andaupro** [hieuhust/ProjectOne#12]
![screenshot_2017-01-21-10-26-23](https://cloud.githubusercontent.com/assets/20449588/22171627/71cae808-dfc4-11e6-9d29-69a25646627c.png)
**======================**
![screenshot_20170121-102229](https://cloud.githubusercontent.com/assets/20449588/22171628/726613b4-dfc4-11e6-9c33-aed2a6902911.png)

**Comment by hieuhust** [comment]
Tôi nghĩ 2 trường hợp này nó đều không ảnh hưởng đến tính thẩm mỹ của giao diện nên. Cả 2 trông đều đẹp nên không sao
