### ISSUE TITLE
Hiển thị vị trí xe trên bản đồ

### ISSUE THREAD

**Issue by hieuhust** [hieuhust/ProjectOne#5]
1. Dựa vào kinh đỗ, vị đỗ hiển thị vị trí của xe trên bản đồ. (Lưu ý về sau có thể liên tục nhận dữ liệu realtime từ server nên cần thiết kế cho hợp lý)
2. Lưu ý hình ảnh của xe khi người dùng zoom in, zoom out bản đồ. (Follow theo app vcomsat)

**Comment by andaupro** [comment]
done

**Comment by hieuhust** [comment]
1. Kiểm tra mạng có bật không, nếu chưa bật thì báo họ là nên bật thì mới sang map.
2. Ông xem cho xe bé thêm 1 chút để trông nó đẹp như trong app mẫu được không

**Comment by hieuhust** [comment]
Tôi test trên LG LTE2. 
Độ phân giải 480 x 800 pixels
Kích thước màn hình
4.7 inches

**Comment by andaupro** [comment]
done
