### ISSUE TITLE
Dự vào dữ liệu thô, vẽ lại đường đi của xe trên bản đồ.

### ISSUE THREAD

**Issue by hieuhust** [hieuhust/ProjectOne#7]
1. Dựa vào dữ liệu thô, vẽ lại đường đi của xe trên bản đồ.
2. Thêm các icon chỉ đánh dấu là tại vị trí đó xe dừng lại. Khi bấm vào icon đó, sẽ hiển thị chi tiết xe dừng tại đó bao nhiêu phút...(Tham khảo app vcomsat)
2. Mô phỏng xe chạy trên đường đi.
3. Lưu ý khi zoom in, zoom out

**Comment by andaupro** [comment]
done 90%

**Comment by hieuhust** [comment]
1. Ở hộp thoại thông báo mạng,nút bấm Ok để hơi bé gây khó khăn khi bấm vào đó => Để to hơn 1 chút.
2.Hộp thoại cũng hơi to so với nội dung 1 chút. Nên để bé hơn 1 tí cho phù hợp.
3. Nội dung hộp thoại đang dùng tiếng anh. App mình đang tập trung vào tiếng Việt đầu tiên => nên thêm tiếng việt mặc định nữa.
4. Ở phần bản đồ, nên 2 marker nên đánh hiển thị A và B như app mẫu, để biết đầu là điểm đầu, đâu là điểm cuối
5. Nên fake đường đi dễ nhìn hơn 1 tí, để tiện theo dõi xe đi đúng hay sai + lúc demo  nhìn nó dễ hơn, đẹp hơn
6. Icon xe nên thay cái khác cho đẹp hơn.
7. Trong app mẫu xe có cái chỉ hướng. Ông xem có làm đươc không?
8.. Cái spiner hơi khó nhìn=> Chỉnh lại màu chữ
![device-2017-01-18-095948](https://cloud.githubusercontent.com/assets/4771954/22049296/fa8dd162-dd64-11e6-9b1e-051072658aad.png)

**Comment by hieuhust** [comment]
Ở phần xem lại:
1. Khi hộp thoại báo không có mạng xuất hiện, người dùng bật mạng => bấm ok. App không tiếp tục phần map mà vẫn quay lại màn hình trước  đó.
2. Khi người dùng chọn tốc độ nên lưu vào share preference để lần sau hiển thị lại đúng tốc độ người dùng đã chọn.(Tham khảo file _com.anonymous.carchecker.common.data.PreferencesUtil_ để dùng. File này để dùng lưu đối tượng vào preference. Đối tượng chỉ cần kế thừa DataModel là lưu được)

**Comment by hieuhust** [comment]
Tôi test trên LG LTE2. 
Độ phân giải 480 x 800 pixels
Kích thước màn hình
4.7 inches

**Comment by andaupro** [comment]
1.Ở hộp thoại thông báo mạng,nút bấm Ok để hơi bé gây khó khăn khi bấm vào đó => Để to hơn 1 chút.**[DONE]**
2.Hộp thoại cũng hơi to so với nội dung 1 chút. Nên để bé hơn 1 tí cho phù hợp.**[DONE]**
3.Nội dung hộp thoại đang dùng tiếng anh. App mình đang tập trung vào tiếng Việt đầu tiên => nên thêm tiếng việt mặc định nữa.**[DONE]**
4.Ở phần bản đồ, nên 2 marker nên đánh hiển thị A và B như app mẫu, để biết đầu là điểm đầu, đâu là điểm cuối.**[DONE]**
5.Nên fake đường đi dễ nhìn hơn 1 tí, để tiện theo dõi xe đi đúng hay sai + lúc demo nhìn nó dễ hơn, đẹp hơn.**[DONE]**
6.Icon xe nên thay cái khác cho đẹp hơn.**[DONE]**
7.Trong app mẫu xe có cái chỉ hướng. Ông xem có làm đươc không?**[DONE]**

**Comment by andaupro** [comment]
1.Khi hộp thoại báo không có mạng xuất hiện, người dùng bật mạng => bấm ok. App không tiếp tục phần map mà vẫn quay lại màn hình trước đó. 
**# <===== Tôi check app gốc thấy nó không check mạng khi mở map, dù load map được hay không vẫn cứ chạy mô phỏng, vậy : 
(1) Vẫn check mạng hay làm giống app gốc?
(2)nếu vẫn check mạng thì tôi nghĩ khi bấm đồng ý nên thoát khỏi activity dù cho ng dùng có bật mạng lại trước hay chưa... ông nên follow theo các app khác**

**Comment by andaupro** [comment]
2.Khi người dùng chọn tốc độ nên lưu vào share preference để lần sau hiển thị lại đúng tốc độ người dùng đã chọn.(Tham khảo file com.anonymous.carchecker.common.data.PreferencesUtil để dùng. File này để dùng lưu đối tượng vào preference. Đối tượng chỉ cần kế thừa DataModel là lưu được). **[DONE]**

**Comment by andaupro** [comment]
8. Cái spiner hơi khó nhìn=> Chỉnh lại màu chữ **[DONE]**

**Comment by andaupro** [comment]
Done
